#!/bin/sh

ENCUT_OPT=$1
KPOINT_OPT=$2

deltab=4.046152088     #la idea es que este valor sea tomado del OUTCAR donde dice length of vectors, debajo del enunciado esta el valor de 4.046152088 o la linea 2138 solo que copie el primer valor 

for a in  -0.07 -0.05 -0.04 -0.03 -0.02 -0.01 -0.005 0.0 0.005 0.01 0.02 0.03 0.04 0.05 0.07     # porcentaje deseo introduccir en la ecuacion de abajo b
do
#echo "a= $a"
 b=$(perl -e 'print $ARGV[0] * (1+$ARGV[1])**(1/3)' $deltab $a)        # esta sería la ecuacion para realizar la curva de Energía vs Volumen
 echo $b

cat >POSCAR <<!
Al FCC
$b
1.00  0.00  0.00                  
0.00  1.00  0.00
0.00  0.00  1.00
4
Direct
0.00000000 0.00000000 0.0000000
0.50000000 0.00000000 0.5000000
0.50000000 0.50000000 0.0000000
0.00000000 0.50000000 0.5000000
!
cat >INCAR << !

SYSTEM =  Cu3Sb 1x1x1
ISMEAR = 2
SIGMA = 0.1
ENCUT = $ENCUT_OPT
ISTART = 0
ICHARG = 2
GGA = 91

ISPIN = 1

ALGO = Normal
LREAL = .FALSE.
NSIM = 4
NELMIN = 4
EDIFFG  = 1E-4
EDIFF = 1E-6

IBRION = 2
POTIM = 0.5
NSW = 400
ISIF  = 2
#NGX = 26 
#NGY = 26
#NGZ = 26

Prec = Accurate 
!

cat >KPOINTS << !
Al 1x1x1
0
Monkhorst Pack
$KPOINT_OPT
0.0 0.0 0.0
!
mpirun -np 4 vasp_std > salida.txt

V=`grep volume/ion OUTCAR|awk '{print $5}'`
E=`tail -n1 OSZICAR | awk '{ print $5/4}'`
T=`grep 'CPU time' OUTCAR |awk '{print $6}'`
P=`grep pressure OUTCAR  |awk '{print $4}'`
totT=`echo $totT $T|awk '{print $1+$2}'`
echo $b $T >> TvsA.dat
echo $b $E >> EvsA.dat
echo $V $E >> EvsV.dat
echo $P $V >> PvsV.dat


done

cat <<! | ./evfit.4
FCC
4
EvsA.dat
EvsVEOS.dat
!

Emin=`grep Emin EvsVEOS.dat|awk '{print $2}'`
A0=`grep A0 EvsVEOS.dat|awk '{print $2}'`
K0=`grep A0 EvsVEOS.dat|awk '{print $4}'`

tail +5 EvsVEOS.dat|awk '{print $1,"\t", $2,"\t", $3}' > grace.dat

echo "Data for Al in FCC" >> SUMMARY
echo "=================================================" >> SUMMARY
echo "Equilibrium Energy per Atom    = $Emin">>SUMMARY
echo "Equilibrium lattice constant   = $A0">>SUMMARY
echo "Bulk Modulus                   = $K0">>SUMMARY
echo "Total CPU time (sec)           = $totT">>SUMMARY
